prometheusOperator:
  enabled: true

prometheus-operator:
  defaultRules:
    create: true
    rules:
      alertmanager: false
      etcd: false
      kubeScheduler: false
  kubeEtcd:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  alertmanager:
    enabled: false

  prometheusOperator:
    image:
      repository: quay.io/coreos/prometheus-operator
      tag: v0.40.0
    tlsProxy:
      image:
        repository: raspbernetes/ghostunnel
        tag: v1.5.2
    prometheusConfigReloaderImage:
      repository: quay.io/coreos/prometheus-config-reloader
      tag: v0.40.0
    configmapReloadImage:
      repository: docker.io/jimmidyson/configmap-reload
      tag: v0.4.0
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 60m
        memory: 100Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values:
                - "true"

  kube-state-metrics:
    image:
      repository: raspbernetes/kube-state-metrics
      tag: v1.9.7
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 60m
        memory: 100Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values:
                - "true"

  grafana:
    replicas: 1
    grafana.ini:
      server:
        root_url: https://grafana.gudari.io
        domain: grafana.gudari.io
        enforce_domain: false
        enable_gzip: true
      auth:
        disable_login_form: true
      auth.generic_oauth:
        enabled: true
        allow_sign_up: true
        name: Auth0
        client_id: dcT8QSQ6Ux4sArrpkf6391S2HHFED6EI
        client_secret: GA_MaZdNXrolWahNVRRUv3oowgu8Q0WqdBaMbrXdmVV9Px1AHPCuiQ_n_8MvjN0a 
        scopes: "openid profile email"
        auth_url: https://dev-se96zcxp.eu.auth0.com/authorize
        token_url: https://dev-se96zcxp.eu.auth0.com/oauth/token
        api_url: https://dev-se96zcxp.eu.auth0.com/userinfo
    sidecar:
      image:
        repository: raspbernetes/k8s-sidecar
        tag: 0.1.144
    adminPassword: prom-operator
    ingress:
      enabled: true
      hosts:
      - grafana.gudari.io
      annotations:
        kubernetes.io/tls-acme: "true"
      tls:
      - secretName: grafana-tls
        hosts:
        - grafana.gudari.io
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 210m
        memory: 512Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values:
                - "true"
    persistence:
      enabled: true
      size: 5Gi

  prometheus-node-exporter:
    image:
      repository: quay.io/prometheus/node-exporter
      tag: v1.0.0
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 60m
        memory: 100Mi

  prometheus:
    ingress:
      enabled: true
      hosts:
      - prometheus.gudari.io
      annotations:
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/auth-url: https://auth0.gudari.io/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://auth0.gudari.io/oauth2/start?rd=https://$host$request_uri
      tls:
      - secretName: prometheus-tls
        hosts:
        - prometheus.gudari.io
    prometheusSpec:
      replicas: 1
      retention: 3d
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "node-role.kubernetes.io/master"
                  operator: In
                  values:
                  - "true"
      resources:
        requests:
          cpu: 750m
          memory: 2Gi
        limits:
          cpu: 800m
          memory: 2Gi
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 5Gi