replicas: 1

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

image:
  repository: gudari/zookeeper-rest
  tag: 3.6.1-arm64
  pullPolicy: Always

podAntiAffinity: "soft"

services:
  rest:
    port: 9998
    targetPort: 9998
    protocol: TCP

resources: {}

nodeSelector: {}

tolerations: []

config:
  REST_PROPERTIES_rest_port: "9998"
  REST_PROPERTIES_rest_endpoint_1: /\;rpizoo-zookeeper-zookeeper-0.rpizoo-zookeeper-zookeeper.zookeeper.svc.cluster.local:2181,rpizoo-zookeeper-zookeeper-1.rpizoo-zookeeper-zookeeper.zookeeper.svc.cluster.local:2181,rpizoo-zookeeper-zookeeper-2.rpizoo-zookeeper-zookeeper.zookeeper.svc.cluster.local:2181

publishNotReadyAddresses: true

ingress:
  enabled: true
  hosts:
  - zookeeper-rest.192.168.1.151.nip.io
  path: /
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "tls-ca-issuer"
  tls: true
