apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kylin.fullname" . }}-configmap
  labels:
    app: {{ include "kylin.name" . }}
    chart: {{ include "kylin.chart" . }}
    release: {{ .Release.Name }}
data:
  HADOOP_CLUSTER_NAME: 'local'
  # Core configurations
  CORE_CONF_fs_defaultFS: hdfs://rpi-hadoop-hadoop-hdfs-namenode-0.rpi-hadoop-hadoop-hdfs-namenode.rpi-hadoop.svc.cluster.local:8020
  CORE_CONF_hadoop_http_staticuser_user: root
  CORE_CONF_hadoop_proxyuser_hue_hosts: '*'
  CORE_CONF_hadoop_proxyuser_hue_groups: '*'
  CORE_CONF_hadoop_proxyuser_root_hosts: '*'
  CORE_CONF_hadoop_proxyuser_root_groups: '*'
  CORE_CONF_hadoop_proxyuser_admin_hosts: '*'
  CORE_CONF_hadoop_proxyuser_admin_groups: '*'
  CORE_CONF_hadoop_http_cross___origin_enabled: "true"
  CORE_CONF_hadoop_http_cross___origin_allowed___origins: "*"
  CORE_CONF_hadoop_http_cross___origin_allowed___methods: PUT,GET,POST,HEAD,DELETE,OPTIONS
  CORE_CONF_hadoop_http_cross___origin_allowed___headers: X-Requested-With,Content-Type,Accept,Origin
  CORE_CONF_hadoop_http_cross___origin_max___age: "1800"
  CORE_CONF_hadoop_proxyuser_nfsserver_groups: '*'
  CORE_CONF_hadoop_proxyuser_nfsserver_hosts: '*'
  # Hdfs configurations
  HDFS_CONF_dfs_namenode_name_dir: file:///hadoop/dfs/name
  HDFS_CONF_dfs_datanode_data_dir: file:///hadoop/dfs/data
  HDFS_CONF_dfs_webhdfs_enabled: "true"
  HDFS_CONF_dfs_permissions_enabled: "false"
  HDFS_CONF_dfs_datanode_use_datanode_hostname: "false"
  HDFS_CONF_dfs_client_use_datanode_hostname: "false"
  HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: "false"
  HDFS_CONF_dfs_datanode_http_address: 0.0.0.0:50075
  HDFS_CONF_dfs_namenode_http___address: 0.0.0.0:50070
  HDFS_CONF_dfs_hosts_exclude: /opt/hadoop/etc/hadoop/dfs.exclude
  HDFS_CONF_dfs_namenode_heartbeat_recheck___interval: "150000"
  HDFS_CONF_dfs_namenode_accesstime_precision: '3600000'
  HDFS_CONF_dfs_nfs3_dump_dir: "/tmp/.hdfs-nfs"
  HDFS_CONF_dfs_nfs_exports_allowed_hosts: "* rw"
  # Mapred configurations
  MAPRED_CONF_mapreduce_framework_name: yarn
  MAPRED_CONF_mapreduce_map_memory_mb: "1536"
  MAPRED_CONF_mapreduce_map_java_opts: -Xmx1024M
  MAPRED_CONF_mapreduce_reduce_memory_mb: "3072"
  MAPRED_CONF_mapreduce_reduce_java_opts: -Xmx2560M
  MAPRED_CONF_mapreduce_task_io_sort_mb: "512"
  MAPRED_CONF_mapreduce_task_io_sort_factor: "100"
  MAPRED_CONF_mapreduce_reduce_shuffle_parallelcopies: "50"
  MAPRED_CONF_mapreduce_application_classpath: $HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*,$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*,$HADOOP_MAPRED_HOME/share/hadoop/common/*,$HADOOP_MAPRED_HOME/share/hadoop/common/lib/*,$HADOOP_MAPRED_HOME/share/hadoop/yarn/*,$HADOOP_MAPRED_HOME/share/hadoop/yarn/lib/*,$HADOOP_MAPRED_HOME/share/hadoop/hdfs/*,$HADOOP_MAPRED_HOME/share/hadoop/hdfs/lib/*
  MAPRED_CONF_mapreduce_map_env: HADOOP_MAPRED_HOME=$HADOOP_HOME
  MAPRED_CONF_mapreduce_reduce_env: HADOOP_MAPRED_HOME=$HADOOP_HOME
  ## History server configuration
  MAPRED_CONF_mapreduce_jobhistory_address: rpi-hadoop-hadoop-mapred-historyserver-0.rpi-hadoop-hadoop-mapred-historyserver.rpi-hadoop.svc.cluster.local:10020
  MAPRED_CONF_mapreduce_jobhistory_webapp_address: rpi-hadoop-hadoop-mapred-historyserver-0.rpi-hadoop-hadoop-mapred-historyserver.rpi-hadoop.svc.cluster.local:19888
  MAPRED_CONF_mapreduce_jobhistory_intermediate__done__dir: /mr-history/tmp
  MAPRED_CONF_mapreduce_jobhistory_done__dir: /mr-history/done
  # Yarn configurations
  YARN_CONF_yarn_log___aggregation___enable: "true"
  YARN_CONF_yarn_resourcemanager_recovery_enabled: "true"
  YARN_CONF_yarn_resourcemanager_store_class: org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
  YARN_CONF_yarn_resourcemanager_fs_state___store_uri: /rmstate
  YARN_CONF_yarn_nodemanager_remote___app___log___dir: /app-logs
  YARN_CONF_yarn_log_server_url: http://rpi-hadoop-hadoop-yarn-timelineserver.rpi-hadoop-hadoop-yarn-timelineserver.rpi-hadoop.svc.cluster.local:8188/applicationhistory/logs/
  YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled: "true"
  YARN_CONF_yarn_resourcemanager_hostname: rpi-hadoop-hadoop-yarn-resourcemanager-0.rpi-hadoop-hadoop-yarn-resourcemanager.rpi-hadoop.svc.cluster.local
  YARN_CONF_yarn_resourcemanager_address: rpi-hadoop-hadoop-yarn-resourcemanager-0.rpi-hadoop-hadoop-yarn-resourcemanager.rpi-hadoop.svc.cluster.local:8032
  YARN_CONF_yarn_resourcemanager_scheduler_address: rpi-hadoop-hadoop-yarn-resourcemanager-0.rpi-hadoop-hadoop-yarn-resourcemanager.rpi-hadoop.svc.cluster.local:8030
  YARN_CONF_yarn_resourcemanager_resource___tracker_address: rpi-hadoop-hadoop-yarn-resourcemanager-0.rpi-hadoop-hadoop-yarn-resourcemanager.rpi-hadoop.svc.cluster.local:8031
  YARN_CONF_yarn_app_mapreduce_am_env: HADOOP_MAPRED_HOME=$HADOOP_HOME
  YARN_CONF_yarn_application_classpath: $HADOOP_CONF_DIR,$HADOOP_COMMON_HOME/share/hadoop/common/*,$HADOOP_COMMON_HOME/share/hadoop/common/lib/*,$HADOOP_HDFS_HOME/share/hadoop/hdfs/*,$HADOOP_HDFS_HOME/share/hadoop/hdfs/lib/*,$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*,$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*,$HADOOP_YARN_HOME/share/hadoop/yarn/*,$HADOOP_YARN_HOME/share/hadoop/yarn/lib/*
  YARN_CONF_yarn_nodemanager_aux___services: mapreduce_shuffle
  YARN_CONF_yarn_nodemanager_aux___services_mapreduce__shuffle_class: org.apache.hadoop.mapred.ShuffleHandler
  YARN_CONF_yarn_nodemanager_address: 0.0.0.0:45454
  ## Timeline server configuration
  YARN_CONF_yarn_timeline___service_enabled: "true"
  YARN_CONF_yarn_timeline___service_hostname: rpi-hadoop-hadoop-yarn-timelineserver-0.rpi-hadoop-hadoop-yarn-timelineserver.rpi-hadoop.svc.cluster.local
  YARN_CONF_yarn_timeline___service_leveldb___timeline___store_path: /hadoop/yarn/timeline
  YARN_CONF_yarn_timeline___service_generic___application___history_enabled: "true"
  YARN_CONF_yarn_timeline___service_http___cross___origin_enabled: "true"
  ## Hive configuration
  HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName: 'org.postgresql.Driver'
  HIVE_SITE_CONF_javax_jdo_option_ConnectionURL: 'jdbc:postgresql://rpi-hive-postgresql:5432/hive?createDatabaseIfNotExist=true'
  HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName: hive
  HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword: hive123
  HIVE_SITE_CONF_hive_metastore_warehouse_dir: "hdfs://rpi-hadoop-hadoop-hdfs-namenode-0.rpi-hadoop-hadoop-hdfs-namenode.rpi-hadoop.svc.cluster.local:8020/user/hive/warehouse"
  HIVE_SITE_CONF_hive_metastore_uris: "thrift://rpi-hive-hive-metastore-0.rpi-hive-hive-metastore.rpi-hive.svc.cluster.local:9083"
  HIVE_SITE_CONF_hive_metastore_schema_verification: "true"
  HIVE_SITE_CONF_datanucleus_autoCreateSchema: "true"
  HIVE_SITE_CONF_datanucleus_fixedDatastore: "true"
  HIVE_SITE_CONF_hive_server2_webui_host: 0.0.0.0
  HIVE_SITE_CONF_hive_server2_webui_port: "10002"
  HIVE_SITE_CONF_hive_server2_thrift_bind_host: rpi-hive-hive-hiveserver2-0.rpi-hive-hive-hiveserver2.rpi-hive.svc.cluster.local
  ## Hbase configuration
  HBASE_CONF_hbase_rootdir: hdfs://rpi-hadoop-hadoop-hdfs-namenode-0.rpi-hadoop-hadoop-hdfs-namenode.rpi-hadoop.svc.cluster.local:8020/hbase
  HBASE_CONF_hbase_cluster_distributed: "true"
  HBASE_CONF_hbase_zookeeper_quorum: rpi-zookeeper-zookeeper-0.rpi-zookeeper-zookeeper.rpi-zookeeper.svc.cluster.local
  HBASE_CONF_hbase_master: rpi-hbase-hbase-master-0.rpi-hbase-hbase-master.rpi-hbase.svc.cluster.local:16000
  HBASE_CONF_hbase_master_hostname: rpi-hbase-hbase-master-0.rpi-hbase-hbase-master.rpi-hbase.svc.cluster.local
  HBASE_CONF_hbase_master_port: "16000"
  HBASE_CONF_hbase_master_info_port: "16010"
  HBASE_CONF_hbase_regionserver_port: "16020"
  HBASE_CONF_hbase_regionserver_info_port: "16030"
  ## Kylin configuration
  KYLIN_PROPERTIES_kylin_storage_url: hbase
  KYLIN_PROPERTIES_kylin_storage_hbase_table___name___prefix: KYLIN_
  KYLIN_PROPERTIES_kylin_storage_hbase_namespace: default
  KYLIN_PROPERTIES_kylin_storage_hbase_cluster___fs: hdfs://rpi-hadoop-hadoop-hdfs-namenode-0.rpi-hadoop-hadoop-hdfs-namenode.rpi-hadoop.svc.cluster.local:8020

  KYLIN_HIVE_CONF_dfs_replication: "1"
  KYLIN_HIVE_CONF_hive_exec_compress_output: "true"
  KYLIN_HIVE_CONF_hive_auto_convert_join: "true"
  KYLIN_HIVE_CONF_hive_auto_convert_join_noconditionaltask: "true"
  KYLIN_HIVE_CONF_hive_auto_convert_join_noconditionaltask_size: "100000000"
  KYLIN_HIVE_CONF_mapreduce_job_split_metainfo_maxsize: "-1"
  KYLIN_HIVE_CONF_hive_stats_autogather: "true"
  KYLIN_HIVE_CONF_hive_merge_mapfiles: "false"
  KYLIN_HIVE_CONF_hive_merge_mapredfiles: "false"

  KYLIN_JOB_CONF_INMEM_mapreduce_job_is___mem___hungry: "true"
  KYLIN_JOB_CONF_INMEM_mapreduce_job_split_metainfo_maxsize: "-1"
  KYLIN_JOB_CONF_INMEM_mapreduce_map_output_compress: "true"
  KYLIN_JOB_CONF_INMEM_mapreduce_output_fileoutputformat_compress_type: BLOCK
  KYLIN_JOB_CONF_INMEM_mapreduce_job_max_split_locations: "2000"
  KYLIN_JOB_CONF_INMEM_dfs_replication: "2"
  KYLIN_JOB_CONF_INMEM_mapreduce_task_timeout: "7200000"
  KYLIN_JOB_CONF_INMEM_mapreduce_map_memory_mb: "3072"
  KYLIN_JOB_CONF_INMEM_mapreduce_map_java_opts: "-Xmx2700m -XX:OnOutOfMemoryError=\'kill -9 %p\'"
  KYLIN_JOB_CONF_INMEM_mapreduce_task_io_sort_mb: "200"

  KYLIN_JOB_CONF_mapreduce_job_split_metainfo_maxsize: "-1"
  KYLIN_JOB_CONF_mapreduce_map_output_compress: "true"
  KYLIN_JOB_CONF_mapreduce_output_fileoutputformat_compress: "true"
  KYLIN_JOB_CONF_mapreduce_output_fileoutputformat_compress_type: BLOCK
  KYLIN_JOB_CONF_mapreduce_job_max_split_locations: "2000"
  KYLIN_JOB_CONF_dfs_replication: "2"
  KYLIN_JOB_CONF_mapreduce_task_timeout: "3600000"

  KYLIN_KAFKA_CONSUMER_session_timeout_ms: "10000"
  KYLIN_KAFKA_CONSUMER_request_timeout_ms: "20000"
