{{- if .Values.broker.enabled }}
{{- if .Values.broker.service.outside.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-broker-public
  labels:
    app: {{ include "kafka.name" . }}
    chart: {{ include "kafka.chart" . }}
    release: {{ .Release.Name }}
    component: broker
spec:
  type: {{ .Values.broker.service.outside.type }}
  ports:
  - name: outside
    port: {{ .Values.broker.ports.outside.containerPort }}
    targetPort: {{ .Values.broker.ports.outside.containerPort }}
    protocol: {{ .Values.broker.ports.outside.protocol }}
  loadBalancerIP: {{ .Values.broker.service.outside.loadBalancerIP }}
  selector:
    app: {{ include "kafka.name" . }}
    release: {{ .Release.Name }}
    component: broker
{{- end }}
{{- end }}
