
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-broker-public
  labels:
    app: {{ include "kafka.name" . }}
    chart: {{ include "kafka.chart" . }}
    release: {{ .Release.Name }}
    component: broker
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: broker  
    port: 31090
    targetPort: 31090
    protocol: TCP
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  selector:
    app: {{ include "kafka.name" . }}
    release: {{ .Release.Name }}
    component: broker