{{- if .Values.broker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-broker
  labels:
    app: {{ include "kafka.name" . }}
    chart: {{ include "kafka.chart" . }}
    release: {{ .Release.Name }}
    component: broker
spec:
{{- if .Values.broker.publishNotReadyAddresses }}
  publishNotReadyAddresses: true
{{- end }}
  ports:
  {{- range $key, $port := .Values.broker.ports }}
  - name: {{ $key }}
    port: {{ $port.containerPort }}
    targetPort: {{ $key }}
    protocol: {{ $port.protocol }}
  {{- end }}
  clusterIP: None
  selector:
    app: {{ include "kafka.name" . }}
    release: {{ .Release.Name }}
    component: broker
{{- end }}
