apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.fullname" . }}-configmap
  labels:
    app: {{ include "kafka.name" . }}
    chart: {{ include "kafka.chart" . }}
    release: {{ .Release.Name }}
data:
  SERVER_PROPERTIES_broker_id: "0"
  SERVER_PROPERTIES_num_network_threads: "3"
  SERVER_PROPERTIES_num_io_threads: "8"
  SERVER_PROPERTIES_socket_send_buffer_bytes: "102400"
  SERVER_PROPERTIES_socket_receive_buffer_bytes: "102400"
  SERVER_PROPERTIES_socket_request_max_bytes: "104857600"
  SERVER_PROPERTIES_log_dirs: /tmp/kafka-logs
  SERVER_PROPERTIES_num_partitions: "1"
  SERVER_PROPERTIES_num_recovery_threads_per_data_dir: "1"
  SERVER_PROPERTIES_offsets_topic_replication_factor: "1"
  SERVER_PROPERTIES_transaction_state_log_replication_factor: "1"
  SERVER_PROPERTIES_transaction_state_log_min_isr: "1"
  SERVER_PROPERTIES_log_retention_hours: "168"
  SERVER_PROPERTIES_log_segment_bytes: "1073741824"
  SERVER_PROPERTIES_log_retention_check_interval_ms: "300000"
  SERVER_PROPERTIES_zookeeper_connect: rpi-zookeeper-zookeeper-0.rpi-zookeeper-zookeeper.rpi-zookeeper.svc.cluster.local:2181
  SERVER_PROPERTIES_zookeeper_connection_timeout_ms: "6000"
  SERVER_PROPERTIES_group_initial_rebalance_delay_ms: "0"
  SERVER_PROPERTIES_inter_broker_listener_name: INTERNAL
  SERVER_PROPERTIES_listeners: INTERNAL://:9092,EXTERNAL://:31090
  SERVER_PROPERTIES_advertised_listeners: EXTERNAL://kafka.gudari.io:31090,INTERNAL://rpi-kafka-kafka-broker-0.rpi-kafka-kafka-broker.rpi-kafka.svc.cluster.local:9092
  SERVER_PROPERTIES_listener_security_protocol_map: INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
