jenkins:
  enabled: true

  controller:
    image: "gudari/jenkins"
    tag: "2.289.1"
    adminUser: "admin"
    adminPassword: "admin123"
    resources:
      requests:
        cpu: "512m"
        memory: "1024Mi"
      limits:
        cpu: "2000m"
        memory: "2048Mi"

    # List of plugins to be install during Jenkins master start
    installPlugins:
      - kubernetes:1.30.0
      - workflow-aggregator:2.6
      - git:4.7.2
      - configuration-as-code:1.54
    installLatestPlugins: true
  
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values:
                - "true"
    ingress:
      enabled: true
      hostName: jenkins.gudari.io
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"
      tls:
      - secretName: jenkins-tls
        hosts:
        - jenkins.gudari.io
    initContainerEnv:
      - name: JENKINS_UC_DOWNLOAD
        value: "http://archives.jenkins-ci.org"

  agent:
    image: "gudari/jenkins-agent"
    tag: "4.9"
    alwaysPullImage: false
    yamlTemplate: |-
      apiVersion: v1
      kind: Pod
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: "node-role.kubernetes.io/master"
                    operator: NotIn
                    values:
                    - "true"
    resources:
      requests:
        cpu: "1000m"
        memory: "2048Mi"
      limits:
        cpu: "1000m"
        memory: "2048Mi"

  persistence:
    enabled: true
    size: "5Gi"
