apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "cm-ca.fullname" . }}-issuer
  labels:
    app: {{ include "cm-ca.name" . }}
    {{- include "cm-ca.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "cm-ca.fullname" . }}-secret
