{{- if .Values.hdfs.nameNode.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.fullname" . }}-hdfs-namenode
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: hdfs-namenode
spec:
{{- if .Values.hdfs.nameNode.publishNotReadyAddresses }}
  publishNotReadyAddresses: true
{{- end }}
  ports:
  {{- range $key, $port := .Values.hdfs.nameNode.ports }}
  - name: {{ $key }}
    port: {{ $port.containerPort }}
    targetPort: {{ $key }}
    protocol: {{ $port.protocol }}
  {{- end }}
  clusterIP: None
  selector:
    app: {{ include "hadoop.name" . }}
    release: {{ .Release.Name }}
    component: hdfs-namenode
{{- end }}
