{{- if .Values.yarn.timeLineServer.enabled }}
{{- if .Values.persistence.timeLineServer.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "hadoop.fullname" . }}-yarn-timelineserver
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: yarn-timelineserver
spec:
  accessModes:
  - {{ .Values.persistence.timeLineServer.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.timeLineServer.size | quote }}
{{- if .Values.persistence.timeLineServer.storageClass }}
{{- if (eq "-" .Values.persistence.timeLineServer.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.timeLineServer.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
{{- end }}