{{- if .Values.tez.ui.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hadoop.fullname" . }}-tez-ui
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: tez-ui
spec:
  rules:
  - host: tez-ui.gudari.io
    http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: {{ include "hadoop.fullname" . }}-tez-ui
            port:
              number: 8080
        path: /
  tls:
  - hosts:
    - tez-ui.gudari.io
{{- end -}}
