apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hadoop.fullname" . }}-configmap
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
data:
  HADOOP_CLUSTER_NAME: 'local'
  # Core configurations
  CORE_CONF_fs_defaultFS: hdfs://{{ include "hadoop.fullname" . }}-hdfs-namenode-0.{{ include "hadoop.fullname" . }}-hdfs-namenode.{{ .Release.Namespace }}.svc.cluster.local:8020
  CORE_CONF_hadoop_http_staticuser_user: root
  CORE_CONF_hadoop_proxyuser_hue_hosts: '*'
  CORE_CONF_hadoop_proxyuser_hue_groups: '*'
  CORE_CONF_hadoop_proxyuser_root_hosts: '*'
  CORE_CONF_hadoop_proxyuser_root_groups: '*'
  CORE_CONF_hadoop_proxyuser_admin_hosts: '*'
  CORE_CONF_hadoop_proxyuser_admin_groups: '*'
  CORE_CONF_hadoop_http_cross___origin_enabled: "true"
  CORE_CONF_hadoop_http_cross___origin_allowed___origins: "*"
  CORE_CONF_hadoop_http_cross___origin_allowed___methods: PUT,GET,POST,HEAD,DELETE,OPTIONS
  CORE_CONF_hadoop_http_cross___origin_allowed___headers: X-Requested-With,Content-Type,Accept,Origin
  CORE_CONF_hadoop_http_cross___origin_max___age: "1800"
  CORE_CONF_hadoop_proxyuser_nfsserver_groups: '*'
  CORE_CONF_hadoop_proxyuser_nfsserver_hosts: '*'
  # Hdfs configurations
  HDFS_CONF_dfs_namenode_name_dir: file:///hadoop/dfs/name
  HDFS_CONF_dfs_datanode_data_dir: file:///hadoop/dfs/data
  HDFS_CONF_dfs_webhdfs_enabled: "true"
  HDFS_CONF_dfs_permissions_enabled: "false"
  HDFS_CONF_dfs_datanode_use_datanode_hostname: "false"
  HDFS_CONF_dfs_client_use_datanode_hostname: "false"
  HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: "false"
  HDFS_CONF_dfs_datanode_http_address: 0.0.0.0:50075
  HDFS_CONF_dfs_namenode_http___address: 0.0.0.0:50070
  HDFS_CONF_dfs_hosts_exclude: /opt/hadoop/etc/hadoop/dfs.exclude
  HDFS_CONF_dfs_namenode_heartbeat_recheck___interval: "150000"
  HDFS_CONF_dfs_namenode_accesstime_precision: '3600000'
  HDFS_CONF_dfs_nfs3_dump_dir: "/tmp/.hdfs-nfs"
  HDFS_CONF_dfs_nfs_exports_allowed_hosts: "* rw"
  # Mapred configurations
  MAPRED_CONF_mapreduce_framework_name: yarn
  MAPRED_CONF_mapreduce_map_memory_mb: "1536"
  MAPRED_CONF_mapreduce_map_java_opts: -Xmx1024M
  MAPRED_CONF_mapreduce_reduce_memory_mb: "3072"
  MAPRED_CONF_mapreduce_reduce_java_opts: -Xmx2560M
  MAPRED_CONF_mapreduce_task_io_sort_mb: "512"
  MAPRED_CONF_mapreduce_task_io_sort_factor: "100"
  MAPRED_CONF_mapreduce_reduce_shuffle_parallelcopies: "50"
  MAPRED_CONF_mapreduce_application_classpath: $HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*,$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*,$HADOOP_MAPRED_HOME/share/hadoop/common/*,$HADOOP_MAPRED_HOME/share/hadoop/common/lib/*,$HADOOP_MAPRED_HOME/share/hadoop/yarn/*,$HADOOP_MAPRED_HOME/share/hadoop/yarn/lib/*,$HADOOP_MAPRED_HOME/share/hadoop/hdfs/*,$HADOOP_MAPRED_HOME/share/hadoop/hdfs/lib/*,$TEZ_CONF_DIR,$TEZ_JARS/*,$TEZ_JARS/lib/*
  MAPRED_CONF_mapreduce_map_env: HADOOP_MAPRED_HOME=$HADOOP_HOME
  MAPRED_CONF_mapreduce_reduce_env: HADOOP_MAPRED_HOME=$HADOOP_HOME
  ## History server configuration
  MAPRED_CONF_mapreduce_jobhistory_address: {{ include "hadoop.fullname" . }}-mapred-historyserver-0.{{ include "hadoop.fullname" . }}-mapred-historyserver.{{ .Release.Namespace }}.svc.cluster.local:10020
  MAPRED_CONF_mapreduce_jobhistory_webapp_address: {{ include "hadoop.fullname" . }}-mapred-historyserver-0.{{ include "hadoop.fullname" . }}-mapred-historyserver.{{ .Release.Namespace }}.svc.cluster.local:19888
  MAPRED_CONF_mapreduce_jobhistory_intermediate__done__dir: /mr-history/tmp
  MAPRED_CONF_mapreduce_jobhistory_done__dir: /mr-history/done
  # Yarn configurations
  YARN_CONF_yarn_log___aggregation___enable: "true"
  YARN_CONF_yarn_resourcemanager_recovery_enabled: "true"
  YARN_CONF_yarn_resourcemanager_store_class: org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
  YARN_CONF_yarn_resourcemanager_fs_state___store_uri: /rmstate
  YARN_CONF_yarn_nodemanager_remote___app___log___dir: /app-logs
  YARN_CONF_yarn_log_server_url: http://{{ include "hadoop.fullname" . }}-yarn-timelineserver.{{ include "hadoop.fullname" . }}-yarn-timelineserver.{{ .Release.Namespace }}.svc.cluster.local:8188/applicationhistory/logs/
  YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled: "true"
  YARN_CONF_yarn_resourcemanager_hostname: {{ include "hadoop.fullname" . }}-yarn-resourcemanager-0.{{ include "hadoop.fullname" . }}-yarn-resourcemanager.{{ .Release.Namespace }}.svc.cluster.local
  YARN_CONF_yarn_resourcemanager_address: {{ include "hadoop.fullname" . }}-yarn-resourcemanager-0.{{ include "hadoop.fullname" . }}-yarn-resourcemanager.{{ .Release.Namespace }}.svc.cluster.local:8032
  YARN_CONF_yarn_resourcemanager_scheduler_address: {{ include "hadoop.fullname" . }}-yarn-resourcemanager-0.{{ include "hadoop.fullname" . }}-yarn-resourcemanager.{{ .Release.Namespace }}.svc.cluster.local:8030
  YARN_CONF_yarn_resourcemanager_resource___tracker_address: {{ include "hadoop.fullname" . }}-yarn-resourcemanager-0.{{ include "hadoop.fullname" . }}-yarn-resourcemanager.{{ .Release.Namespace }}.svc.cluster.local:8031
  YARN_CONF_yarn_app_mapreduce_am_env: HADOOP_MAPRED_HOME=$HADOOP_HOME
  YARN_CONF_yarn_application_classpath: $HADOOP_CONF_DIR,$HADOOP_COMMON_HOME/share/hadoop/common/*,$HADOOP_COMMON_HOME/share/hadoop/common/lib/*,$HADOOP_HDFS_HOME/share/hadoop/hdfs/*,$HADOOP_HDFS_HOME/share/hadoop/hdfs/lib/*,$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*,$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*,$HADOOP_YARN_HOME/share/hadoop/yarn/*,$HADOOP_YARN_HOME/share/hadoop/yarn/lib/*,$TEZ_CONF_DIR,$TEZ_JARS/*,$TEZ_JARS/lib/*
  YARN_CONF_yarn_nodemanager_aux___services: mapreduce_shuffle,tez_shuffle
  YARN_CONF_yarn_nodemanager_aux___services_mapreduce__shuffle_class: org.apache.hadoop.mapred.ShuffleHandler
  YARN_CONF_yarn_nodemanager_aux___services_tez__shuffle_class: org.apache.tez.auxservices.ShuffleHandler
  YARN_CONF_yarn_nodemanager_address: 0.0.0.0:45454
  ## Timeline server configuration
  YARN_CONF_yarn_timeline___service_enabled: "true"
  YARN_CONF_yarn_timeline___service_hostname: {{ include "hadoop.fullname" . }}-yarn-timelineserver-0.{{ include "hadoop.fullname" . }}-yarn-timelineserver.{{ .Release.Namespace }}.svc.cluster.local
  YARN_CONF_yarn_timeline___service_leveldb___timeline___store_path: /hadoop/yarn/timeline
  YARN_CONF_yarn_timeline___service_generic___application___history_enabled: "true"
  YARN_CONF_yarn_timeline___service_http___cross___origin_enabled: "true"
  ## Tez UI configuration
  TEZ_UI_TIMELINE_SERVER: https://timelineserver.gudari.io
  TEZ_UI_RESOURCE_MANAGER: https://resourcemanager.gudari.io
  TEZ_UI_RESOURCE_MANAGER_WEB_PROXY: https://resourcemanager.gudari.io
  TEZ_SITE_tez_lib_uris: /apps/tez-0.10.0/tez.tar.gz
  TEZ_SITE_tez_use_cluster_hadoop___libs: "false"
  TEZ_SITE_tez_runtime_compress: "false"
  TEZ_SITE_tez_am_resource_memory_mb: "1536"
  TEZ_SITE_tez_task_resource_memory_mb: "1024"
  TEZ_SITE_tez_am_java_opts: -Xmx3278m
  TEZ_SITE_tez_history_logging_service_class: org.apache.tez.dag.history.logging.ats.ATSHistoryLoggingService
  TEZ_SITE_tez_tez___ui_history___url_base: http://tez-ui:8080/tez-ui/
  TEZ_SITE_tez_am_shuffle_auxiliary___service_id: tez_shuffle
