{{- if .Values.yarn.nodeManager.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-yarn-nodemanager
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/hadoop-configmap.yaml") . | sha256sum }}
{{- with .Values.yarn.nodeManager.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: yarn-nodemanager
spec:
  serviceName: {{ include "hadoop.fullname" . }}-yarn-nodemanager
  replicas: {{ .Values.yarn.nodeManager.replicas }}
  selector:
    matchLabels:
      app: {{ include "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: yarn-nodemanager
{{- if .Values.yarn.nodeManager.parallelCreate }}
  podManagementPolicy: Parallel
{{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/hadoop-configmap.yaml") . | sha256sum }}
{{- with .Values.yarn.nodeManager.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
        app: {{ include "hadoop.name" . }}
        release: {{ .Release.Name }}
        component: yarn-nodemanager
    spec:
      affinity:
    {{- if .Values.yarn.nodeManager.affinity }}
{{ toYaml .Values.yarn.nodeManager.affinity | indent 8 }}
    {{- end }}
        {{- if eq .Values.yarn.nodeManager.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ include "hadoop.name" . }}
                release: {{ .Release.Name | quote }}
                component: yarn-nodemanager
        {{- else if eq .Values.yarn.nodeManager.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  {{ include "hadoop.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: yarn-nodemanager
        {{- end }}
{{- if .Values.yarn.nodeManager.securityContext }}
      securityContext:
{{ toYaml .Values.yarn.nodeManager.securityContext | indent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 60
      containers:
      - name: yarn-nodemanager
        image: "{{ .Values.yarn.nodeManager.image.repository }}:{{ .Values.yarn.nodeManager.image.tag }}"
        imagePullPolicy: {{ .Values.yarn.nodeManager.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.yarn.nodeManager.resources | indent 10 }}
        ports:
{{- range $key, $port := .Values.yarn.nodeManager.ports }}
        - name: {{ $key }}
{{ toYaml $port | indent 10 }}
{{- end }}
        startupProbe:
          httpGet:
            path: /node
            port: {{ .Values.yarn.nodeManager.ports.api.containerPort }}
{{- with .Values.yarn.nodeManager.startupProbe }}
{{ toYaml . | indent 10 }}
{{- end }}
        readinessProbe:
          httpGet:
            path: /node
            port: {{ .Values.yarn.nodeManager.ports.api.containerPort }}
{{- with .Values.yarn.nodeManager.readinessProbe }}
{{ toYaml . | indent 10 }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /node
            port: {{ .Values.yarn.nodeManager.ports.api.containerPort }}
{{- with .Values.yarn.nodeManager.livenessProbe }}
{{ toYaml . | indent 10 }}
{{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "hadoop.fullname" . }}-configmap
{{- end }}
