{{- if .Values.tez.ui.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-tez-ui
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/hadoop-configmap.yaml") . | sha256sum }}
{{- with .Values.tez.ui.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: tez-ui
spec:
  serviceName: {{ include "hadoop.fullname" . }}-tez-ui
  replicas: {{ .Values.tez.ui.replicas }}
  selector:
    matchLabels:
      app: {{ include "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: tez-ui
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/hadoop-configmap.yaml") . | sha256sum }}
{{- with .Values.tez.ui.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
        app: {{ include "hadoop.name" . }}
        release: {{ .Release.Name }}
        component: tez-ui
    spec:
    {{- with .Values.tez.ui.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
    {{- end }}
      affinity:
    {{- if .Values.tez.ui.affinity }}
{{ toYaml .Values.tez.ui.affinity | indent 8 }}
    {{- end }}
        {{- if eq .Values.tez.ui.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ include "hadoop.name" . }}
                release: {{ .Release.Name | quote }}
                component: tez-ui
        {{- else if eq .Values.tez.ui.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  {{ include "hadoop.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: tez-ui
        {{- end }}
{{- if .Values.tez.ui.securityContext }}
      securityContext:
{{ toYaml .Values.tez.ui.securityContext | indent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 60
      containers:
      - name: tez-ui
        image: "{{ .Values.tez.ui.image.repository }}:{{ .Values.tez.ui.image.tag }}"
        imagePullPolicy: {{ .Values.tez.ui.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.tez.ui.resources | indent 10 }}
        ports:
{{- range $key, $port := .Values.tez.ui.ports }}
        - name: {{ $key }}
{{ toYaml $port | indent 10 }}
{{- end }}
        startupProbe:
          httpGet:
            path: /health
            port: {{ .Values.tez.ui.ports.http.containerPort }}
{{- with .Values.tez.ui.startupProbe }}
{{ toYaml . | indent 10 }}
{{- end }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.tez.ui.ports.http.containerPort }}
{{- with .Values.tez.ui.readinessProbe }}
{{ toYaml . | indent 10 }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.tez.ui.ports.http.containerPort }}
{{- with .Values.tez.ui.livenessProbe }}
{{ toYaml . | indent 10 }}
{{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "hadoop.fullname" . }}-configmap
{{- end }}
