apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hadoop.fullname" . }}-configmap
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key}}: {{ $value }}
{{- end }}

  HADOOP_CLUSTER_NAME: 'local'
  # Core configurations
  CORE_SITE_XML_fs_defaultFS: hdfs://{{ include "hadoop.fullname" . }}-hdfs-namenode-0.{{ include "hadoop.fullname" . }}-hdfs-namenode.{{ .Release.Namespace }}.svc.cluster.local:8020
  CORE_SITE_XML_hadoop_http_staticuser_user: hadoop
  CORE_SITE_XML_hadoop_proxyuser_hue_hosts: '*'
  CORE_SITE_XML_hadoop_proxyuser_hue_groups: '*'
  CORE_SITE_XML_hadoop_proxyuser_hadoop_hosts: '*'
  CORE_SITE_XML_hadoop_proxyuser_hadoop_groups: '*'
  CORE_SITE_XML_fs_trash_interval: "360"
  CORE_SITE_XML_hadoop_http_authentication_simple_anonymous_allowed: "true"
  CORE_SITE_XML_hadoop_security_auth___to___local: DEFAULT
  CORE_SITE_XML_hadoop_http_cross___origin_enabled: "true"
  CORE_SITE_XML_hadoop_http_cross___origin_allowed___origins: "*"
  CORE_SITE_XML_hadoop_http_cross___origin_allowed___methods: PUT,GET,POST,HEAD,DELETE,OPTIONS
  CORE_SITE_XML_hadoop_http_cross___origin_allowed___headers: X-Requested-With,Content-Type,Accept,Origin
  CORE_SITE_XML_hadoop_http_cross___origin_max___age: "1800"
  CORE_SITE_XML_hadoop_proxyuser_nfsserver_groups: '*'
  CORE_SITE_XML_hadoop_proxyuser_nfsserver_hosts: '*'

  # Hdfs configurations
  HDFS_SITE_XML_dfs_namenode_name_dir: file:///hadoop/dfs/name
  HDFS_SITE_XML_dfs_datanode_data_dir: file:///hadoop/dfs/data
  HDFS_SITE_XML_dfs_webhdfs_enabled: "true"
  HDFS_SITE_XML_dfs_permissions_superusergroup: hadoop
  HDFS_SITE_XML_dfs_permissions_enabled: "true"
  HDFS_SITE_XML_dfs_cluster_administrators: hadoop
  HDFS_SITE_XML_dfs_replication: "2"
  HDFS_SITE_XML_dfs_datanode_use_datanode_hostname: "false"
  HDFS_SITE_XML_dfs_client_use_datanode_hostname: "false"
  HDFS_SITE_XML_dfs_namenode_datanode_registration_ip___hostname___check: "false"
  HDFS_SITE_XML_dfs_datanode_http_address: 0.0.0.0:50075
  HDFS_SITE_XML_dfs_namenode_http___address: 0.0.0.0:50070
  HDFS_SITE_XML_dfs_hosts_exclude: /opt/hadoop/etc/hadoop/dfs.exclude
  HDFS_SITE_XML_dfs_namenode_heartbeat_recheck___interval: "150000"
  HDFS_SITE_XML_dfs_namenode_accesstime_precision: '3600000'
  HDFS_SITE_XML_dfs_nfs3_dump_dir: "/tmp/.hdfs-nfs"
  HDFS_SITE_XML_dfs_nfs_exports_allowed_hosts: "* rw"

  # Mapred configurations
  MAPRED_SITE_XML_mapreduce_framework_name: yarn
  MAPRED_SITE_XML_mapreduce_map_memory_mb: "1536"
  MAPRED_SITE_XML_mapreduce_map_java_opts: -Xmx1024M
  MAPRED_SITE_XML_mapreduce_reduce_memory_mb: "3072"
  MAPRED_SITE_XML_mapreduce_reduce_java_opts: -Xmx2560M
  MAPRED_SITE_XML_mapreduce_task_io_sort_mb: "512"
  MAPRED_SITE_XML_mapreduce_task_io_sort_factor: "100"
  MAPRED_SITE_XML_mapreduce_reduce_shuffle_parallelcopies: "50"
  MAPRED_SITE_XML_mapreduce_application_classpath: $HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*,$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*,$HADOOP_MAPRED_HOME/share/hadoop/common/*,$HADOOP_MAPRED_HOME/share/hadoop/common/lib/*,$HADOOP_MAPRED_HOME/share/hadoop/yarn/*,$HADOOP_MAPRED_HOME/share/hadoop/yarn/lib/*,$HADOOP_MAPRED_HOME/share/hadoop/hdfs/*,$HADOOP_MAPRED_HOME/share/hadoop/hdfs/lib/* ##,$TEZ_CONF_DIR,$TEZ_JARS/*,$TEZ_JARS/lib/*
  MAPRED_SITE_XML_mapreduce_map_env: HADOOP_MAPRED_HOME=$HADOOP_HOME
  MAPRED_SITE_XML_mapreduce_reduce_env: HADOOP_MAPRED_HOME=$HADOOP_HOME

  ## History server configuration
  MAPRED_SITE_XML_mapreduce_jobhistory_address: {{ include "hadoop.fullname" . }}-mapred-historyserver-0.{{ include "hadoop.fullname" . }}-mapred-historyserver.{{ .Release.Namespace }}.svc.cluster.local:10020
  MAPRED_SITE_XML_mapreduce_jobhistory_webapp_address: {{ include "hadoop.fullname" . }}-mapred-historyserver-0.{{ include "hadoop.fullname" . }}-mapred-historyserver.{{ .Release.Namespace }}.svc.cluster.local:19888
  MAPRED_SITE_XML_mapreduce_jobhistory_intermediate__done__dir: /mr-history/tmp
  MAPRED_SITE_XML_mapreduce_jobhistory_done__dir: /mr-history/done

  # Yarn configurations
  YARN_SITE_XML_yarn_log___aggregation___enable: "true"
  YARN_SITE_XML_yarn_resourcemanager_recovery_enabled: "true"
  YARN_SITE_XML_yarn_resourcemanager_store_class: org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
  YARN_SITE_XML_yarn_resourcemanager_fs_state___store_uri: /rmstate
  YARN_SITE_XML_yarn_nodemanager_remote___app___log___dir: /app-logs
  YARN_SITE_XML_yarn_log_server_url: http://{{ include "hadoop.fullname" . }}-yarn-timelineserver.{{ include "hadoop.fullname" . }}-yarn-timelineserver.{{ .Release.Namespace }}.svc.cluster.local:8188/applicationhistory/logs/
  YARN_SITE_XML_yarn_resourcemanager_system___metrics___publisher_enabled: "true"
  YARN_SITE_XML_yarn_resourcemanager_hostname: {{ include "hadoop.fullname" . }}-yarn-resourcemanager-0.{{ include "hadoop.fullname" . }}-yarn-resourcemanager.{{ .Release.Namespace }}.svc.cluster.local
  YARN_SITE_XML_yarn_resourcemanager_address: {{ include "hadoop.fullname" . }}-yarn-resourcemanager-0.{{ include "hadoop.fullname" . }}-yarn-resourcemanager.{{ .Release.Namespace }}.svc.cluster.local:8032
  YARN_SITE_XML_yarn_resourcemanager_scheduler_address: {{ include "hadoop.fullname" . }}-yarn-resourcemanager-0.{{ include "hadoop.fullname" . }}-yarn-resourcemanager.{{ .Release.Namespace }}.svc.cluster.local:8030
  YARN_SITE_XML_yarn_resourcemanager_resource___tracker_address: {{ include "hadoop.fullname" . }}-yarn-resourcemanager-0.{{ include "hadoop.fullname" . }}-yarn-resourcemanager.{{ .Release.Namespace }}.svc.cluster.local:8031
  YARN_SITE_XML_yarn_app_mapreduce_am_env: HADOOP_MAPRED_HOME=$HADOOP_HOME
  YARN_SITE_XML_yarn_application_classpath: $HADOOP_CONF_DIR,$HADOOP_COMMON_HOME/share/hadoop/common/*,$HADOOP_COMMON_HOME/share/hadoop/common/lib/*,$HADOOP_HDFS_HOME/share/hadoop/hdfs/*,$HADOOP_HDFS_HOME/share/hadoop/hdfs/lib/*,$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*,$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*,$HADOOP_YARN_HOME/share/hadoop/yarn/*,$HADOOP_YARN_HOME/share/hadoop/yarn/lib/* #,$TEZ_CONF_DIR,$TEZ_JARS/*,$TEZ_JARS/lib/*
  YARN_SITE_XML_yarn_nodemanager_aux___services: mapreduce_shuffle #,tez_shuffle
  YARN_SITE_XML_yarn_nodemanager_aux___services_mapreduce__shuffle_class: org.apache.hadoop.mapred.ShuffleHandler
#  YARN_SITE_XML_yarn_nodemanager_aux___services_tez__shuffle_class: org.apache.tez.auxservices.ShuffleHandler
  YARN_SITE_XML_yarn_nodemanager_address: 0.0.0.0:45454
  YARN_SITE_XML_yarn_web___proxy_address: {{ index .Values.yarn.resourceManager.ingress.hosts 0 }}

  ## Timeline server configuration
  YARN_SITE_XML_yarn_timeline___service_enabled: "true"
  YARN_SITE_XML_yarn_timeline___service_hostname: {{ include "hadoop.fullname" . }}-yarn-timelineserver-0.{{ include "hadoop.fullname" . }}-yarn-timelineserver.{{ .Release.Namespace }}.svc.cluster.local
  YARN_SITE_XML_yarn_timeline___service_leveldb___timeline___store_path: /hadoop/yarn/timeline
  YARN_SITE_XML_yarn_timeline___service_generic___application___history_enabled: "true"
  YARN_SITE_XML_yarn_timeline___service_http___cross___origin_enabled: "true"
  ## Tez UI configuration
#  TEZ_UI_TIMELINE_SERVER: https://timelineserver.gudari.io
#  TEZ_UI_RESOURCE_MANAGER: https://resourcemanager.gudari.io
#  TEZ_UI_RESOURCE_MANAGER_WEB_PROXY: https://resourcemanager.gudari.io
#  TEZ_SITE_XML_tez_lib_uris: /apps/tez-0.10.1/tez.tar.gz
#  TEZ_SITE_XML_tez_use_cluster_hadoop___libs: "false"
#  TEZ_SITE_XML_tez_runtime_compress: "false"
#  TEZ_SITE_XML_tez_am_resource_memory_mb: "1536"
#  TEZ_SITE_XML_tez_task_resource_memory_mb: "1024"
#  TEZ_SITE_XML_tez_am_java_opts: -Xmx3278m
#  TEZ_SITE_XML_tez_history_logging_service_class: org.apache.tez.dag.history.logging.ats.ATSHistoryLoggingService
#  TEZ_SITE_XML_tez_tez___ui_history___url_base: http://tez-ui:8080/tez-ui/
#  TEZ_SITE_XML_tez_am_shuffle_auxiliary___service_id: tez_shuffle
