{{- if .Values.tez.ui.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-tez-ui
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/hadoop-configmap.yaml") . | sha256sum }}
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: tez-ui
spec:
  serviceName: {{ include "hadoop.fullname" . }}-tez-ui
  replicas: {{ .Values.tez.ui.replicas }}
  selector:
    matchLabels:
      app: {{ include "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: tez-ui
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/hadoop-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ include "hadoop.name" . }}
        release: {{ .Release.Name }}
        component: tez-ui
    spec:
      affinity:
        podAntiAffinity:
        {{- if eq .Values.tez.ui.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ include "hadoop.name" . }}
                release: {{ .Release.Name | quote }}
                component: tez-ui
        {{- else if eq .Values.tez.ui.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  {{ include "hadoop.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: tez-ui
        {{- end }}
      terminationGracePeriodSeconds: 0
      containers:
      - name: tez-ui
        image: "{{ .Values.tez.ui.image.repository }}:{{ .Values.tez.ui.image.tag }}"
        imagePullPolicy: {{ .Values.tez.ui.image.pullPolicy | quote }}
        ports:
        - containerPort: 8080
          name: web
        resources:
{{ toYaml .Values.tez.ui.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 2
        envFrom:
        - configMapRef:
            name: {{ include "hadoop.fullname" . }}-configmap
{{- end }}