{{- if .Values.mapred.historyServer.enableIngress -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "hadoop.fullname" . }}-tez-ui
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: tez-ui
spec:
  rules:
  - host: tez-ui.gudari.io
    http:
      paths:
      - backend:
          serviceName: {{ include "hadoop.fullname" . }}-tez-ui
          servicePort: web
        path: /
  tls:
  - hosts:
    - tez-ui.gudari.io
{{- end -}}
