{{- if .Values.yarn.timeLineServer.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-yarn-timelineserver
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/hadoop-configmap.yaml") . | sha256sum }}
{{- with .Values.yarn.timeLineServer.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: yarn-timelineserver
spec:
  serviceName: {{ include "hadoop.fullname" . }}-yarn-timelineserver
  replicas: {{ .Values.yarn.timeLineServer.replicas }}
  selector:
    matchLabels:
      app: {{ include "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: yarn-timelineserver
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/hadoop-configmap.yaml") . | sha256sum }}
{{- with .Values.yarn.timeLineServer.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
        app: {{ include "hadoop.name" . }}
        release: {{ .Release.Name }}
        component: yarn-timelineserver
    spec:
    {{- with .Values.yarn.timeLineServer.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
    {{- end }}
      affinity:
    {{- if .Values.hdfs.nameNode.affinity }}
{{ toYaml .Values.hdfs.nameNode.affinity | indent 8 }}
    {{- end }}
        {{- if eq .Values.yarn.timeLineServer.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ include "hadoop.name" . }}
                release: {{ .Release.Name | quote }}
                component: yarn-timelineserver
        {{- else if eq .Values.yarn.timeLineServer.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  {{ include "hadoop.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: yarn-timelineserver
        {{- end }}
      terminationGracePeriodSeconds: 0
      containers:
      - name: yarn-timelineserver
        image: "{{ .Values.yarn.timeLineServer.image.repository }}:{{ .Values.yarn.timeLineServer.image.tag }}"
        imagePullPolicy: {{ .Values.yarn.timeLineServer.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.yarn.timeLineServer.resources | indent 10 }}
        ports:
{{- range $key, $port := .Values.yarn.timeLineServer.ports }}
        - name: {{ $key }}
{{ toYaml $port | indent 10 }}
{{- end }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.yarn.timeLineServer.ports.http.containerPort }}
          initialDelaySeconds: 120
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.yarn.timeLineServer.ports.http.containerPort }}
          initialDelaySeconds: 120
          timeoutSeconds: 2
        envFrom:
        - configMapRef:
            name: {{ include "hadoop.fullname" . }}-configmap
{{- if .Values.persistence.timeLineServer.enabled }}
        volumeMounts:
        - name: store
          mountPath: /hadoop/yarn/timeline
  volumeClaimTemplates:
  - metadata:
      name: store
    spec:
      accessModes:
        - {{ .Values.persistence.timeLineServer.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.timeLineServer.size | quote }}
    {{- if .Values.persistence.timeLineServer.storageClass }}
    {{- if (eq "-" .Values.persistence.timeLineServer.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.persistence.timeLineServer.storageClass }}"
    {{- end }}
    {{- end }}
      {{- else }}
      volumes:
        - name: store
          emptyDir: {}
      {{- end }}
{{- end }}
