
# A headless service to create datanodeS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.fullname" . }}-master
  labels:
    app: {{ include "spark.name" . }}
    chart: {{ include "spark.chart" . }}
    release: {{ .Release.Name }}
    component: master
spec:
  ports:
{{- range $key, $service := .Values.master.services }}
    - name: {{ $key }}
      port: {{ $service.port }}
      targetPort: {{ $service.targetPort }}
      protocol: {{ $service.protocol }}
{{- end }}
  clusterIP: None
  selector:
    app: {{ include "spark.name" . }}
    release: {{ .Release.Name }}
    component: master