
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeppelin.fullname" . }}-zeppelin
  labels:
    app: {{ include "zeppelin.name" . }}
    chart: {{ include "zeppelin.chart" . }}
    release: {{ .Release.Name }}
    component: zeppelin
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: {{ include "zeppelin.name" . }}
    release: {{ .Release.Name }}
    component: zeppelin