replicas: 1

updateStrategy:
  type: RollingUpdate

image:
  repository: gudari/nifi
  tag: 1.12.1-arm64
  pullPolicy: Always

podAntiAffinity: "soft"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
            - "rpi-slave-2"

services:
  web:
    port: 8080
    targetPort: 8080
    protocol: TCP

resources:
  requests:
    memory: "1Gi"
    cpu: "0.5"
  limits:
    memory: "1Gi"
    cpu: "0.5"

nodeSelector: {}

tolerations: []

config: {}

publishNotReadyAddresses: true

persistence:
  enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
  - nifi.gudari.io
  extraPaths: []
  tls:
  - secretName: nifi-tls
    hosts:
    - nifi.gudari.io