apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zookeeperrest.fullname" . }}-configmap
  labels:
    app: {{ include "zookeeperrest.name" . }}
    chart: {{ include "zookeeperrest.chart" . }}
    release: {{ .Release.Name }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key}}: {{ $value | quote }}
{{- end }}
