{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "zookeeperrest.fullname" . }}-zookeeper-rest
  labels:
    app: {{ include "zookeeperrest.name" . }}
    chart: {{ include "zookeeperrest.chart" . }}
    release: {{ .Release.Name }}
    component: zookeeper-rest
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
{{- range $host := .Values.ingress.hosts }}
  - host: "{{ $host }}"
    http:
      paths:
      - backend:
          serviceName: {{ include "zookeeperrest.fullname" $ }}-zookeeper-rest
          servicePort: {{ $.Values.services.rest.port }}
        path: {{ $.Values.ingress.path }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
  {{ toYaml .Values.ingress.hosts | indent 4 }}
    secretName: {{ include "zookeeperrest.fullname" . }}-zookeeper-rest
{{- end }}
{{- end }}