
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-airflow
  labels:
    app: {{ include "airflow.name" . }}
    chart: {{ include "airflow.chart" . }}
    release: {{ .Release.Name }}
    component: airflow
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: {{ include "airflow.name" . }}
    release: {{ .Release.Name }}
    component: airflow