mongodb:
  enabled: true

  image:
    repository: "arm64v8/mongo"
    tag: "4.2.9-bionic"
  
  useStatefulSet: true
  
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
              - "rpi-slave-1"
  resources:
    requests:
      memory: "1Gi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "300m"
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.203
  persistence:
    enabled: true
    mountPath: /data/db
    size: 5Gi

