apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "storm.fullname" . }}-nimbus
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/storm-configmap.yaml") . | sha256sum }}
  labels:
    app: {{ include "storm.name" . }}
    chart: {{ include "storm.chart" . }}
    release: {{ .Release.Name }}
    component: nimbus
spec:
  serviceName: {{ include "storm.fullname" . }}-nimbus
  replicas: {{ .Values.nimbus.replicas }}
  selector:
    matchLabels:
      app: {{ include "storm.name" . }}
      release: {{ .Release.Name }}
      component: nimbus
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/storm-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ include "storm.name" . }}
        release: {{ .Release.Name }}
        component: nimbus
    spec:
      affinity:
    {{- if .Values.nimbus.affinity }}
{{ toYaml .Values.nimbus.affinity | indent 8 }}
    {{- end }}
        podAntiAffinity:
        {{- if eq .Values.nimbus.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ include "storm.name" . }}
                release: {{ .Release.Name | quote }}
                component: nimbus
        {{- else if eq .Values.nimbus.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  {{ include "storm.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: nimbus
        {{- end }}
      terminationGracePeriodSeconds: 0
      containers:
      - name: nimbus
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.nimbus.resources | indent 10 }}
        envFrom:
        - configMapRef:
            name: {{ include "storm.fullname" . }}-configmap
