apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "storm.fullname" . }}-configmap
  labels:
    app: {{ include "storm.name" . }}
    chart: {{ include "storm.chart" . }}
    release: {{ .Release.Name }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key}}: {{ $value }}
{{- end }}

