
# A headless service to create datanodeS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "storm.fullname" . }}-nimbus
  labels:
    app: {{ include "storm.name" . }}
    chart: {{ include "storm.chart" . }}
    release: {{ .Release.Name }}
    component: nimbus
spec:
  ports:
  - name: web
    port: 8081
    protocol: TCP
  clusterIP: None
  selector:
    app: {{ include "storm.name" . }}
    release: {{ .Release.Name }}
    component: nimbus