elasticsearch:
  enabled: true
  image: "docker.elastic.co/elasticsearch/elasticsearch"
  imageTag: "7.9.0"
  imagePullPolicy: "IfNotPresent"

  replicas: 1
  minimumMasterNodes: 1

  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
            - "rpi-slave-1"
  volumeClaimTemplate:
    resources:
      requests:
        storage: 10Gi

  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.202
