elasticsearch:
  enabled: true
  image: "docker.elastic.co/elasticsearch/elasticsearch"
  imageTag: "7.9.0"
  imagePullPolicy: "IfNotPresent"

  replicas: 1
  minimumMasterNodes: 1

  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
            - "rpi-slave-1"
  volumeClaimTemplate:
    resources:
      requests:
        storage: 10Gi
