
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "superset.fullname" . }}-superset
  labels:
    app: {{ include "superset.name" . }}
    chart: {{ include "superset.chart" . }}
    release: {{ .Release.Name }}
    component: superset
spec:
  ports:
  - name: web
    port: 8088
    protocol: TCP
  selector:
    app: {{ include "superset.name" . }}
    release: {{ .Release.Name }}
    component: superset