apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flink-sql-gateway.fullname" . }}-configmap
  labels:
    app: {{ include "flink-sql-gateway.name" . }}
    chart: {{ include "flink-sql-gateway.chart" . }}
    release: {{ .Release.Name }}
data:

{{- range $key, $value := .Values.config }}
  {{ $key}}: {{ $value | quote }}
{{- end }}
