
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flink-sql-gateway.fullname" . }}-flink-sql-gateway
  labels:
    app: {{ include "flink-sql-gateway.name" . }}
    chart: {{ include "flink-sql-gateway.chart" . }}
    release: {{ .Release.Name }}
    component: flink-sql-gateway-namenode
spec:
  ports:
  - name: rest
    port: 8083
    protocol: TCP
  selector:
    app: {{ include "flink-sql-gateway.name" . }}
    release: {{ .Release.Name }}
    component: flink-sql-gateway