---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpi-jupyterhub-serviceaccount
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: rpi-jupyterhub
subjects:
- kind: ServiceAccount
  name: rpi-jupyterhub-serviceaccount
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
