# The base hadoop image to use for all components.
# See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
image:
  repository: gudari/hadoop
  tag: 2.10.1
  pullPolicy: Always #Always

# The version of the hadoop libraries being used in the image.
hadoopVersion: 2.10.1

hdfs:
  nameNode:
    enabled: true
    image:
      repository: gudari/hadoop
      tag: 2.10.1
      pullPolicy: Always
    replicas: 1
    annotations: {}
    antiAffinity: "soft"
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-1"
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "512Mi"
        cpu: "350m"
      limits:
        memory: "512Mi"
        cpu: "400m"
    publishNotReadyAddresses: true
    ports:
      http:
        containerPort: 50070
        protocol: TCP
      ipc:
        containerPort: 8020
        protocol: TCP
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/enable-cors: "true"
      path: /
      hosts:
      - hdfs.gudari.io
      extraPaths: []
      tls:
      - secretName: hdfs-tls
        hosts:
        - hdfs.gudari.io

  dataNode:
    enabled: true
    image:
      repository: gudari/hadoop
      tag: 2.10.1
      pullPolicy: Always
    replicas: 3
    annotations: {}
    antiAffinity: "soft"
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-2"
                - "rpi-slave-3"
                - "rpi-slave-4"
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "512Mi"
        cpu: "350m"
      limits:
        memory: "512Mi"
        cpu: "400m"
    publishNotReadyAddresses: true
    ports:
      http:
        containerPort: 50075
        protocol: TCP
      data:
        containerPort: 50010
        protocol: TCP
      ipc:
        containerPort: 50020
        protocol: TCP
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 20Gi
    servicePerReplica:
      enabled: true
      type: ClusterIP
      port: 50075
      targetPort: 50075
    ingressPerReplica:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/enable-cors: "true"
      path: /
      hostPrefix: datanode
      domains:
      - gudari.io
      extraPaths: []
      tls:
      - secretName: hdfs-tls
        domains:
        - gudari.io
  nfsGateway:
    enabled: false
    image:
      repository: gudari/hadoop
      tag: 2.10.1
      pullPolicy: Always
    replicas: 0
    annotations: {}
    antiAffinity: ""
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-1"
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "512Mi"
        cpu: "350m"
      limits:
        memory: "512Mi"
        cpu: "400m"
    serviceTCP:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: "192.168.1.204"
      annotations:
        metallb.universe.tf/allow-shared-ip: nfs-gateway
      ports:
        nfs-tcp:
          port: 2049
          targetPort: 2049
          protocol: TCP
        mountd-tcp:
          port: 4242
          targetPort: 4242
          protocol: TCP
        portmapper-tcp:
          port: 111
          targetPort: 111
          protocol: TCP
    serviceUDP:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: "192.168.1.204"
      annotations:
        metallb.universe.tf/allow-shared-ip: nfs-gateway
      ports:
        nfs-udp:
          port: 2049
          targetPort: 2049
          protocol: UDP
        mountd-udp:
          port: 4242
          targetPort: 4242
          protocol: UDP
        portmapper-udp:
          port: 111
          targetPort: 111
          protocol: UDP

mapred:
  historyServer:
    enabled: true
    image:
      repository: gudari/hadoop
      tag: 2.10.1
      pullPolicy: Always
    replicas: 1
    annotations: {}
    antiAffinity: "soft"
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-1"
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "512Mi"
        cpu: "450m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    publishNotReadyAddresses: true
    ports:
      http:
        containerPort: 19888
        protocol: TCP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      path: /
      hosts:
      - historyserver.gudari.io
      extraPaths: []
      tls:
      - secretName: historyserver-tls
        hosts:
        - historyserver.gudari.io

yarn:
  resourceManager:
    enabled: true
    image:
      repository: gudari/hadoop
      tag: 2.10.1
      pullPolicy: Always
    replicas: 1
    annotations: {}
    antiAffinity: "soft"
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-1"
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "512Mi"
        cpu: "450m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    publishNotReadyAddresses: true
    ports:
      http:
        containerPort: 8088
        protocol: TCP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      path: /
      hosts:
      - resourcemanager.gudari.io
      extraPaths: []
      tls:
      - secretName: resourcemanager-tls
        hosts:
        - resourcemanager.gudari.io

  nodeManager:
    enabled: true
    image:
      repository: gudari/hadoop
      tag: 2.10.1
      pullPolicy: Always
    replicas: 3
    annotations: {}
    antiAffinity: "soft"
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-2"
                - "rpi-slave-3"
                - "rpi-slave-4"
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "2048Mi"
        cpu: "500m"
      limits:
        memory: "2048Mi"
        cpu: "520m"
    publishNotReadyAddresses: true
    ports:
      http:
        containerPort: 8088
        protocol: TCP
      http2:
        containerPort: 8082
        protocol: TCP
      api:
        containerPort: 8042
        protocol: TCP

  timeLineServer:
    enabled: true
    image:
      repository: gudari/hadoop
      tag: 2.10.1
      pullPolicy: Always
    replicas: 1
    annotations: {}
    antiAffinity: "soft"
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-1"
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "512Mi"
        cpu: "420m"
      limits:
        memory: "512Mi"
        cpu: "450m"
    publishNotReadyAddresses: true
    ports:
      http:
        containerPort: 8188
        protocol: TCP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      path: /
      hosts:
      - timelineserver.gudari.io
      extraPaths: []
      tls:
      - secretName: timelineserver-tls
        hosts:
        - timelineserver.gudari.io

tez:
  ui:
    enabled: false
    image:
      repository: gudari/tez-ui
      tag: 0.10.0-arm64
      pullPolicy: Always
    antiAffinity: "soft"
    replicas: 1
    pdbMinAvailable: 0

    # CPU and memory resources allocated to each node manager pod.
    # This should be tuned to fit your workload.
    resources:
      requests:
        memory: "512Mi"
        cpu: "420m"
      limits:
        memory: "512Mi"
        cpu: "450m"

    enableIngress: true

persistence:
  nameNode:
    enabled: enabled
    storageClass: local-path 
    accessMode: ReadWriteOnce
    size: 5Gi

  dataNode:
    enabled: enabled
    storageClass: local-path 
    accessMode: ReadWriteOnce
    size: 10Gi

  timeLineServer:
    enabled: enabled
    storageClass: local-path 
    accessMode: ReadWriteOnce
    size: 5Gi
