# The base hadoop image to use for all components.
# See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
image:
  repository: gudari/hadoop
  tag: 3.2.2
  pullPolicy: IfNotPresent #Always

# The version of the hadoop libraries being used in the image.
hadoopVersion: 3.2.2

hdfs:
  nameNode:
    enabled: true
    image:
      repository: gudari/hadoop
      tag: 3.2.2
      pullPolicy: IfNotPresent
    replicas: 1
    annotations: {}
    antiAffinity: "soft"
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-1"
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "512Mi"
        cpu: "350m"
      limits:
        memory: "512Mi"
        cpu: "400m"
    publishNotReadyAddresses: true
    ports:
      http:
        containerPort: 50070
        protocol: TCP
      ipc:
        containerPort: 8020
        protocol: TCP
    startupProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      periodSeconds: 30
      successThreshold: 1
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/enable-cors: "true"
      path: /
      hosts:
      - hdfs.gudari.io
      extraPaths: []
      tls:
      - secretName: hdfs-tls
        hosts:
        - hdfs.gudari.io

  dataNode:
    enabled: true
    image:
      repository: gudari/hadoop
      tag: 3.2.2
      pullPolicy: IfNotPresent
    replicas: 3
    annotations: {}
    antiAffinity: "soft"
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-2"
                - "rpi-slave-3"
                - "rpi-slave-4"
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "512Mi"
        cpu: "350m"
      limits:
        memory: "512Mi"
        cpu: "400m"
    publishNotReadyAddresses: true
    ports:
      http:
        containerPort: 50075
        protocol: TCP
      data:
        containerPort: 50010
        protocol: TCP
      ipc:
        containerPort: 50020
        protocol: TCP
    startupProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      periodSeconds: 30
      successThreshold: 1
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 20Gi
    servicePerReplica:
      enabled: true
      type: ClusterIP
      port: 50075
      targetPort: 50075
    ingressPerReplica:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/enable-cors: "true"
      path: /
      hostPrefix: datanode
      domains:
      - gudari.io
      extraPaths: []
      tls:
      - secretName: hdfs-tls
        domains:
        - gudari.io
  nfsGateway:
    enabled: true
    image:
      repository: gudari/hadoop
      tag: 3.2.2
      pullPolicy: IfNotPresent
    replicas: 1
    annotations: {}
    antiAffinity: ""
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-1"
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      sysctls:
      - name: net.ipv4.ip_unprivileged_port_start
        value: "0"
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "512Mi"
        cpu: "350m"
      limits:
        memory: "512Mi"
        cpu: "400m"
    serviceTCP:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: "192.168.1.204"
      annotations:
        metallb.universe.tf/allow-shared-ip: nfs-gateway
      ports:
        nfstcp:
          port: 2049
          targetPort: 2049
          protocol: TCP
        mountdtcp:
          port: 4242
          targetPort: 4242
          protocol: TCP
        portmappertcp:
          port: 111
          targetPort: 111
          protocol: TCP
    serviceUDP:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: "192.168.1.204"
      annotations:
        metallb.universe.tf/allow-shared-ip: nfs-gateway
      ports:
        nfsudp:
          port: 2049
          targetPort: 2049
          protocol: UDP
        mountdudp:
          port: 4242
          targetPort: 4242
          protocol: UDP
        portmapperudp:
          port: 111
          targetPort: 111
          protocol: UDP
    startupProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      periodSeconds: 30
      successThreshold: 1
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1

mapred:
  historyServer:
    enabled: true
    image:
      repository: gudari/hadoop
      tag: 3.2.2
      pullPolicy: IfNotPresent
    replicas: 1
    annotations: {}
    antiAffinity: "soft"
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-1"
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "512Mi"
        cpu: "450m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    publishNotReadyAddresses: true
    ports:
      http:
        containerPort: 19888
        protocol: TCP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"
      path: /
      hosts:
      - historyserver.gudari.io
      extraPaths: []
      tls:
      - secretName: historyserver-tls
        hosts:
        - historyserver.gudari.io
    startupProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      periodSeconds: 30
      successThreshold: 1
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1

yarn:
  resourceManager:
    enabled: true
    image:
      repository: gudari/hadoop
      tag: 3.2.2
      pullPolicy: IfNotPresent
    replicas: 1
    annotations: {}
    antiAffinity: "soft"
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-1"
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "512Mi"
        cpu: "450m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    publishNotReadyAddresses: true
    ports:
      http:
        containerPort: 8088
        protocol: TCP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"
      path: /
      hosts:
      - resourcemanager.gudari.io
      extraPaths: []
      tls:
      - secretName: resourcemanager-tls
        hosts:
        - resourcemanager.gudari.io
    startupProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      periodSeconds: 30
      successThreshold: 1
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1

  nodeManager:
    enabled: true
    image:
      repository: gudari/hadoop
      tag: 3.2.2
      pullPolicy: IfNotPresent
    replicas: 3
    annotations: {}
    antiAffinity: "soft"
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-2"
                - "rpi-slave-3"
                - "rpi-slave-4"
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "2048Mi"
        cpu: "500m"
      limits:
        memory: "2048Mi"
        cpu: "520m"
    publishNotReadyAddresses: true
    ports:
      http:
        containerPort: 8088
        protocol: TCP
      http2:
        containerPort: 8082
        protocol: TCP
      api:
        containerPort: 8042
        protocol: TCP
    startupProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
      failureThreshold: 3
      periodSeconds: 30
      successThreshold: 1
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1
    servicePerReplica:
      enabled: true
      type: ClusterIP
      port: 8042
      targetPort: 8042
    ingressPerReplica:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/enable-cors: "true"
      path: /
      hostPrefix: nodemanager
      domains:
      - gudari.io
      extraPaths: []
      tls:
      - secretName: yarn-tls
        domains:
        - gudari.io

  timeLineServer:
    enabled: true
    image:
      repository: gudari/hadoop
      tag: 3.2.2
      pullPolicy: IfNotPresent
    replicas: 1
    annotations: {}
    antiAffinity: "soft"
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-1"
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "512Mi"
        cpu: "420m"
      limits:
        memory: "512Mi"
        cpu: "450m"
    publishNotReadyAddresses: true
    ports:
      http:
        containerPort: 8188
        protocol: TCP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"
      path: /
      hosts:
      - timelineserver.gudari.io
      extraPaths: []
      tls:
      - secretName: timelineserver-tls
        hosts:
        - timelineserver.gudari.io
    startupProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      periodSeconds: 30
      successThreshold: 1
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 30
      successThreshold: 1

tez:
  ui:
    enabled: false
    image:
      repository: gudari/tez-ui
      tag: 0.10.1-arm64
      pullPolicy: IfNotPresent
    replicas: 1
    annotations: {}
    antiAffinity: "soft"
    nodeSelector: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "rpi-slave-1"
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    pdbMinAvailable: 0
    resources:
      requests:
        memory: "512Mi"
        cpu: "420m"
      limits:
        memory: "512Mi"
        cpu: "450m"
    publishNotReadyAddresses: true
    ports:
      http:
        containerPort: 8080
        protocol: TCP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"
      path: /
      hosts:
      - tez-ui.gudari.io
      extraPaths: []
      tls:
      - secretName: tez-tls
        hosts:
        - tez-ui.gudari.io
    startupProbe:
      initialDelaySeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 10
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 10
      successThreshold: 1

persistence:
  nameNode:
    enabled: enabled
    storageClass: local-path 
    accessMode: ReadWriteOnce
    size: 5Gi

  dataNode:
    enabled: enabled
    storageClass: local-path 
    accessMode: ReadWriteOnce
    size: 10Gi

  timeLineServer:
    enabled: enabled
    storageClass: local-path 
    accessMode: ReadWriteOnce
    size: 5Gi
