apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hbase.fullname" . }}-regionserver
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/hbase-configmap.yaml") . | sha256sum }}
  labels:
    app: {{ include "hbase.name" . }}
    chart: {{ include "hbase.chart" . }}
    release: {{ .Release.Name }}
    component: regionserver
spec:
  serviceName: {{ include "hbase.fullname" . }}-regionserver
  replicas: {{ .Values.regionserver.replicas }}
  selector:
    matchLabels:
      app: {{ include "hbase.name" . }}
      release: {{ .Release.Name }}
      component: regionserver
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/hbase-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ include "hbase.name" . }}
        release: {{ .Release.Name }}
        component: regionserver
    spec:
      affinity:
        podAntiAffinity:
        {{- if eq .Values.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ include "hbase.name" . }}
                release: {{ .Release.Name | quote }}
                component: regionserver
        {{- else if eq .Values.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  {{ include "hbase.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: regionserver
        {{- end }}
      terminationGracePeriodSeconds: 0
      containers:
      - name: regionserver
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.regionserver.resources | indent 10 }}
        readinessProbe:
          tcpSocket:
            port: 16030
          initialDelaySeconds: 120
          timeoutSeconds: 2
          tcpSocket:
            port: 16030
          initialDelaySeconds: 120
          timeoutSeconds: 2
        envFrom:
        - configMapRef:
            name: {{ include "hbase.fullname" . }}-configmap
