
# A headless service to create datanodeS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hbase.fullname" . }}-regionserver
  labels:
    app: {{ include "hbase.name" . }}
    chart: {{ include "hbase.chart" . }}
    release: {{ .Release.Name }}
    component: regionserver
spec:
  ports:
  - name: web
    port: 16030
    protocol: TCP
  clusterIP: None
  selector:
    app: {{ include "hbase.name" . }}
    release: {{ .Release.Name }}
    component: regionserver