{{- if .Values.master.enableIngress -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "hbase.fullname" . }}-master
  labels:
    app: {{ include "hbase.name" . }}
    chart: {{ include "hbase.chart" . }}
    release: {{ .Release.Name }}
    component: master
spec:
  rules:
  - host: hbasemaster.gudari.io
    http:
      paths:
      - backend:
          serviceName: {{ include "hbase.fullname" . }}-master
          servicePort: web
        path: /
  tls:
  - hosts:
    - hbasemaster.gudari.io
{{- end -}}