{{- if .Values.regionserver.enableIngress -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "hbase.fullname" . }}-regionserver
  labels:
    app: {{ include "hbase.name" . }}
    chart: {{ include "hbase.chart" . }}
    release: {{ .Release.Name }}
    component: regionserver
spec:
  rules:
  - host: regionserver.gudari.io
    http:
      paths:
      - backend:
          serviceName: {{ include "hbase.fullname" . }}-regionserver
          servicePort: web
        path: /
  tls:
  - hosts:
    - regionserver.gudari.io
{{- end -}}