
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttyd.fullname" . }}
  labels:
    app: {{ include "ttyd.name" . }}
    chart: {{ include "ttyd.chart" . }}
    release: {{ .Release.Name }}
    component: ttyd-namenode
spec:
  type: ClusterIP
{{- if .Values.publishNotReadyAddresses }}
  publishNotReadyAddresses: true
{{- end }}
  ports:
  {{- range $key, $port := .Values.ports }}
  - name: {{ $key }}
    port: {{ $port.containerPort }}
    targetPort: {{ $key }}
    protocol: {{ $port.protocol }}
  {{- end }}
  selector:
    app: {{ include "ttyd.name" . }}
    release: {{ .Release.Name }}
    component: ttyd
