pihole:
  enabled: true
  image:
    repository: "pihole/pihole"
    tag: "2021.10.1"
  serviceDns:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.200"
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
  serviceDhcp:
    enabled: false
  ingress:
    enabled: true
    hosts:
    - pihole.gudari.io
    annotations:
      kubernetes.io/tls-acme: "true"
    tls:
    - secretName: pihole-tls
      hosts:
      - pihole.gudari.io
  resources:
    limits:
     cpu: 250m
     memory: 128Mi
    requests:
     cpu: 200m
     memory: 128Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/master"
              operator: In
              values:
              - "true"
  adminPassword: "admin"
  dnsmasq:
    customDnsEntries:
      - address=/.gudari.io/192.168.1.201
      - address=/elasticsearch.gudari.io/192.168.1.202
      - address=/mongodb.gudari.io/192.168.1.203
      - address=/nfsgateway.gudari.io/192.168.1.204
      - address=/kafka.gudari.io/192.168.1.205
  whitelist:
  - ads-serve.brave.com
