# The base hadoop image to use for all components.
# See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
enabled: true
image:
  repository: gudari/airflow
  tag: 1.10.13-arm64
  pullPolicy: IfNotPresent #Always

# The version of the hadoop libraries being used in the image.
airflowVersion: 1.10.13

resources:
  requests:
    memory: "512Mi"
    cpu: "300m"
  limits:
    memory: "512Mi"
    cpu: "320m"

config: {}

# Select antiAffinity as either hard or soft, default is soft
antiAffinity: "soft"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
            - "rpi-master"

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  path: ""
  hosts:
  - airflow.gudari.io
  extraPaths: []
  tls:
  - secretName: airflow-tls
    hosts:
    - airflow.gudari.io
