ingress-nginx:
  enabled: true

  rbac:
    create: true
  
  defaultBackend:
    enabled: true
    image:
      registry: k8s.gcr.io
      image: defaultbackend-arm64
      tag: "1.5"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values:
                - "true"
    resources:
      requests:
        cpu: 20m
        memory: 50Mi
      limits:
        cpu: 20m
        memory: 50Mi
  controller:
    image:
      registry: k8s.gcr.io
      repository: ingress-nginx/controller
      tag: v0.47.0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values:
                - "true"
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
      limits:
        cpu: 300m
        memory: 512Mi
    service:
      loadBalancerIP: "192.168.1.200"
      annotations:
        metallb.universe.tf/allow-shared-ip: nginx-ingress-svc
