apiVersion: v1
description: The Apache Hbase Version 2.2.6.
name: hbase
version: 0.0.1
appVersion: 2.2.6
home: https://hbase.apache.org/
sources:
- https://github.com/apache/hbase
icon: https://hbase.apache.org/images/hbase_logo_with_orca_large.png
maintainers:
- name: gudari
  email: aartola1986@gmail.com
