# The base spark image to use for all components.
# See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
image:
  repository: gudari/hbase
  tag: 2.2.6-arm64
  pullPolicy: IfNotPresent #Always

# The version of the hadoop libraries being used in the image.
hbaseVersion: 2.2.6

# Select antiAffinity as either hard or soft, default is soft
antiAffinity: "soft"

master:
  replicas: 1
  pdbMinAvailable: 0
  resources:
    requests:
      memory: "1024Mi"
      cpu: "0.5"
    limits:
      memory: "1024Mi"
      cpu: "0.5"
  enableIngress: true

regionserver:
  replicas: 1
  pdbMinAvailable: 0
  resources:
    requests:
      memory: "1024Mi"
      cpu: "0.5"
    limits:
      memory: "1024Mi"
      cpu: "0.5"

config:
  HADOOP_CLUSTER_NAME: 'local'

  # CORE configurations
  CORE_CONF_fs_defaultFS: hdfs://rpi-hadoop-hadoop-hdfs-namenode-0.rpi-hadoop-hadoop-hdfs-namenode.rpi-hadoop.svc.cluster.local:8020
  CORE_CONF_hadoop_http_staticuser_user: root
  CORE_CONF_hadoop_proxyuser_hue_hosts: "\'*\'"
  CORE_CONF_hadoop_proxyuser_hue_groups: "\'*\'"
  CORE_CONF_hadoop_proxyuser_root_hosts: "\'*\'"
  CORE_CONF_hadoop_proxyuser_root_groups: "\'*\'"
  CORE_CONF_hadoop_proxyuser_admin_hosts: "\'*\'"
  CORE_CONF_hadoop_proxyuser_admin_groups: "\'*\'"

  # HDFS configurations
  HDFS_CONF_dfs_namenode_name_dir: file:///hadoop/dfs/name
  HDFS_CONF_dfs_datanode_data_dir: file:///hadoop/dfs/data
  HDFS_CONF_dfs_webhdfs_enabled: "\"true\""
  HDFS_CONF_dfs_permissions_enabled: "\"false\""
  HDFS_CONF_dfs_datanode_use_datanode_hostname: "\"false\""
  HDFS_CONF_dfs_client_use_datanode_hostname: "\"false\""
  HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: "\"false\""
  HDFS_CONF_dfs_datanode_http_address: "0.0.0.0:50075"
  HDFS_CONF_dfs_namenode_http___address: "0.0.0.0:50070"

  HBASE_CONF_hbase_rootdir: hdfs://rpi-hadoop-hadoop-hdfs-namenode-0.rpi-hadoop-hadoop-hdfs-namenode.rpi-hadoop.svc.cluster.local:8020/hbase
  HBASE_CONF_hbase_cluster_distributed: "\"true\""
  HBASE_CONF_hbase_zookeeper_quorum: rpi-zookeeper-zookeeper-0.rpi-zookeeper-zookeeper.rpi-zookeeper.svc.cluster.local:2181

  HBASE_CONF_hbase_master: rpi-hbase-hbase-master-0.rpi-hbase-hbase-master.rpi-hbase.svc.cluster.local:16000
  HBASE_CONF_hbase_master_hostname: rpi-hbase-hbase-master-0.rpi-hbase-hbase-master.rpi-hbase.svc.cluster.local
  HBASE_CONF_hbase_master_port: "\"16000\""
  HBASE_CONF_hbase_master_info_port: "\"16010\""
  HBASE_CONF_hbase_regionserver_port: "\"16020\""
  HBASE_CONF_hbase_regionserver_info_port: "\"16030\""
  HBASE_CONF_hbase_regionserver_hostname: rpi-hbase-hbase-regionserver-0.rpi-hbase-hbase-regionserver.rpi-hbase.svc.cluster.local

  HBASE_MANAGES_ZK: "\"false\""
