minio:
  image:
    repository: minio/minio
    tag: RELEASE.2021-02-14T04-01-33Z
    pullPolicy: IfNotPresent
  mcImage:
    repository: minio/mc
    tag: RELEASE.2021-02-14T04-28-06Z
    pullPolicy: IfNotPresent
  helmKubectlJqImage:
    repository: bskim45/helm-kubectl-jq
    tag: 3.1.0
    pullPolicy: IfNotPresent
  
  mode: distributed
  
  accessKey: "DdM9TkrbhkR6JBEPkQMRd6vHNfgH99en"
  secretKey: "pGbMzUEiEiCCYwafjn8Rr4COYyxplhhs"
  persistence:
    size: 15Gi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    hosts:
    - minio.gudari.io
    tls:
    - secretName: minio-tls
      hosts:
      - minio.gudari.io
  resources:
    requests:
      memory: 700Mi
      cpu: 100m
  