apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow.fullname" . }}-mlflow
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  labels:
    app: {{ include "mlflow.name" . }}
    chart: {{ include "mlflow.chart" . }}
    release: {{ .Release.Name }}
    component: mlflow
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "mlflow.name" . }}
      release: {{ .Release.Name }}
      component: mlflow
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ include "mlflow.name" . }}
        release: {{ .Release.Name }}
        component: mlflow
    spec:
      affinity:
    {{- if .Values.affinity }}
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
        podAntiAffinity:
        {{- if eq .Values.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ include "mlflow.name" . }}
                release: {{ .Release.Name | quote }}
                component: mlflow
        {{- else if eq .Values.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  {{ include "mlflow.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: mlflow
        {{- end }}
      terminationGracePeriodSeconds: 0
      containers:
      - name: mlflow
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - name: web
          containerPort: 5000
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: "/health"
            port: 5000
          initialDelaySeconds: 60
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: "/health"
            port: 5000
          initialDelaySeconds: 60
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: {{ include "mlflow.fullname" . }}-configmap
